# Generated by Django 4.1.7 on 2023-03-19 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0003_alter_answers_id_questions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answers',
            name='id_questions',
            field=models.IntegerField(verbose_name='Id вопроса'),
        ),
    ]
