# Generated by Django 4.1.7 on 2023-03-19 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0004_alter_answers_id_questions'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Answers',
        ),
    ]
